blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/SayantanCode/cli-project-structure-builder/discussions
    about: Please ask and answer questions here.
