const nextJsPagesRouterBoilerplate = (projectName) => {
  return {
    "package.json": `{
  "name": "${projectName}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {
    "eslint": "latest",
    "eslint-config-next": "latest"
  }
}`,
    ".eslintrc.json": `{
  "extends": "next/core-web-vitals"
}`,
    ".gitignore": `# Dependencies
/node_modules
/.pnp
.pnp.js

# Testing
/coverage

# Next.js
/.next/
/out/

# Production
/build

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Env files
.env*
!.env.example

# Misc
.DS_Store
`,
    "next.config.mjs": `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true
};

export default nextConfig;
`,
    "jsconfig.json": `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["*"]
    }
  }
}`,
    "pages/": {
      "_app.js": `import "@/styles/globals.css";

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
`,
      "index.js": `import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>${projectName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=pages"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=pages"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Docs →</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=pages"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Learn →</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=pages"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Templates →</h2>
            <p>Explore the Next.js templates to jumpstart your app.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=pages"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Deploy →</h2>
            <p>Instantly deploy your Next.js site to a shareable URL with Vercel.</p>
          </a>
        </div>
      </main>
    </>
  );
}
`,
      "api/": {
        "hello.js": `export default function handler(req, res) {
  res.status(200).json({ name: "John Doe" });
}
`
      }
    },
    "public/": {
      "favicon.ico": "[binary placeholder]",
      "next.svg": `<?xml version="1.0" encoding="UTF-8"?>
<!-- simplified Next.js logo svg placeholder -->`,
      "vercel.svg": `<?xml version="1.0" encoding="UTF-8"?>
<!-- simplified Vercel logo svg placeholder -->`,
      "thirteen.svg": `<?xml version="1.0" encoding="UTF-8"?>
<!-- simplified 13 badge svg placeholder -->`
    },
    "styles/": {
      "globals.css": `:root {
  --foreground: #171717;
  --background: #ffffff;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground: #ededed;
    --background: #0a0a0a;
  }
}

html, body {
  padding: 0;
  margin: 0;
  height: 100%;
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

* {
  box-sizing: border-box;
}
`,
      "Home.module.css": `.main {
  min-height: 100vh;
  padding: 6rem 2rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2.5rem;
}

.description {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: .9rem;
  max-width: 960px;
  width: 100%;
}

.code {
  font-weight: 600;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  background: rgba(127,127,127,.1);
  border-radius: .4rem;
  padding: .3rem .5rem;
}

.center {
  display: flex;
  align-items: center;
  justify-content: center;
}

.logo {
  filter: drop-shadow(0 0 1rem rgba(0,0,0,.25));
}

.grid {
  display: grid;
  gap: 1.2rem;
  grid-template-columns: repeat(2, minmax(240px, 1fr));
  max-width: 960px;
  width: 100%;
}

.card {
  padding: 1.2rem 1.4rem;
  border: 1px solid rgba(127,127,127,.2);
  border-radius: .8rem;
  transition: border-color .2s ease, transform .2s ease;
}

.card:hover {
  border-color: rgba(127,127,127,.5);
  transform: translateY(-2px);
}

.card h2 {
  margin: 0 0 .4rem 0;
  font-size: 1.1rem;
}

.card p {
  margin: 0;
  opacity: .8;
}

@media (max-width: 640px) {
  .description {
    flex-direction: column;
    gap: .75rem;
  }
  .grid {
    grid-template-columns: 1fr;
  }
}
`
    }
  };
};
export default nextJsPagesRouterBoilerplate;