const nextJsTsPageRouterBoilerplate = (projectName) => {
  return {
    "package.json": `{
  "name": "${projectName}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.3",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "typescript": "^5.3.0",
    "@types/node": "20.12.7",
    "@types/react": "18.3.3",
    "@types/react-dom": "18.3.0",
    "eslint": "8.57.0",
    "eslint-config-next": "14.2.3"
  }
}`,
    "tsconfig.json": `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}`,
    "pages/": {
      "_app.tsx": `import type { AppProps } from "next/app";
import "../styles/globals.css";

export default function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}`,
      "index.tsx": `import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>${projectName}</title>
        <meta name="description" content="Generated by Next.js Pages Router" />
      </Head>
      <main style={{ padding: "2rem", fontFamily: "sans-serif" }}>
        <h1>Welcome to ${projectName} 🎉</h1>
        <p>This is a Next.js project using the <strong>Pages Router</strong>.</p>
      </main>
    </>
  );
}`,
    },
    "styles/": {
      "globals.css": `html, body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

* {
  box-sizing: border-box;
}`,
    },
    "next-env.d.ts": `/// <reference types="next" />\n/// <reference types="next/image-types/global" />`,
  };
};

export default nextJsTsPageRouterBoilerplate;
